  <script src="<?php echo base_url();?>/public/assets/js/jquery.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/popper.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/bootstrap.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery.easing.1.3.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery.waypoints.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery.stellar.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery.animateNumber.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/bootstrap-datepicker.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery.timepicker.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/owl.carousel.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/jquery.magnific-popup.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/scrollax.min.js"></script>
  <script src="<?php echo base_url();?>/public/assets/js/main.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
